version: '3'
services:
  master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/sample --headless -r 1 -u 2 -t 20s --html /mnt/locust/report.html --master --expect-workers 2

  worker1:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/sample --headless --worker --master-host master

  worker2:
    image: locustio/locust
    volumes:
     - ./:/mnt/locust
    command: -f /mnt/locust/sample --headless --worker --master-host master